feat: Add helm chart
giantswarm/cluster-api-provider-vsphere-app pull request #2
Opened 2021-03-03 14:52 UTC by QuentinBisson

This PR:

- adds the initial helm chart

### Checklist

- [x] Update changelog in CHANGELOG.md.

2021-03-03 19:02 UTC, MarcelMue approved these changes

2021-03-04 10:04 UTC, TheoBrigitte requested changes

2021-03-04 10:04 UTC, TheoBrigitte commented on helm/cluster-api-provider-vsphere/templates/rbac.yaml
> +  name: leader-election-role
```suggestion
  name: {{ include "resource.default.name" . }}-leader-election-role
```

2021-03-04 10:04 UTC, TheoBrigitte commented on helm/cluster-api-provider-vsphere/templates/rbac.yaml
> +  name: default
```suggestion
  name: {{ include "resource.default.name" . }}
```

2021-03-04 10:04 UTC, TheoBrigitte commented on helm/cluster-api-provider-vsphere/templates/rbac.yaml
> +  name: manager-role
```suggestion
  name: {{ include "resource.default.name" . }}-manager-role
```

2021-03-04 10:04 UTC, TheoBrigitte commented on helm/cluster-api-provider-vsphere/templates/rbac.yaml
> +  name: default
```suggestion
  name: {{ include "resource.default.name" . }}
```

2021-03-04 10:04 UTC, TheoBrigitte commented on helm/cluster-api-provider-vsphere/templates/rbac.yaml
> +  name: proxy-role
```suggestion
  name: {{ include "resource.default.name" . }}-proxy-role
```

2021-03-04 10:04 UTC, TheoBrigitte commented on helm/cluster-api-provider-vsphere/templates/rbac.yaml
> +  name: default
```suggestion
  name: {{ include "resource.default.name" . }}
```

2021-03-04 12:30 UTC, kubasobon commented on helm/cluster-api-provider-vsphere/templates/rbac.yaml
> +  name: {{ include "resource.default.name" . }}-leader-election-role
FYI We got rid of all leader-election roles/rolebindings in other controllers

2021-03-04 12:52 UTC, QuentinBisson commented on helm/cluster-api-provider-vsphere/templates/rbac.yaml
> +  name: {{ include "resource.default.name" . }}-leader-election-role
Thanks

2021-03-04 12:55 UTC, QuentinBisson commented on helm/cluster-api-provider-vsphere/templates/rbac.yaml
> +  name: {{ include "resource.default.name" . }}-leader-election-role
I removed them

2021-03-18 09:04 UTC, merged